import React from 'react';
import ReactMarkdown from 'react-markdown';

interface MinutesViewProps {
  minutes: string;
  fileName: string;
  onReset: () => void;
  onBack: () => void;
}

const MinutesView: React.FC<MinutesViewProps> = ({ minutes, fileName, onReset, onBack }) => {
  return (
    <div className="flex flex-col h-full bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
      <div className="p-4 border-b border-gray-200 bg-gray-50 flex justify-between items-center">
        <div>
          <h2 className="text-lg font-semibold text-gray-800">Meeting Minutes</h2>
          <p className="text-sm text-gray-500">Generated by Gemini AI</p>
        </div>
        <button
          onClick={() => {
            const blob = new Blob([minutes], { type: 'text/markdown' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            // Generate a filename based on the original audio file
            const downloadName = fileName ? `${fileName.split('.')[0]}_minutes.md` : 'meeting_minutes.md';
            a.download = downloadName;
            a.click();
            URL.revokeObjectURL(url);
          }}
          className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-indigo-700 bg-indigo-50 border border-indigo-200 rounded-md hover:bg-indigo-100 transition-colors"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
            <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M12 12.75l-3-3m0 0l-3 3m3-3v12" />
          </svg>
          Download .md
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-6 bg-white prose prose-indigo max-w-none">
        <ReactMarkdown>{minutes}</ReactMarkdown>
      </div>

      <div className="p-4 border-t border-gray-200 bg-gray-50 flex justify-between items-center">
        <button
          onClick={onBack}
          className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors shadow-sm flex items-center gap-2"
        >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
            <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
          </svg>
          Back to Transcript
        </button>
        <button
          onClick={onReset}
          className="text-sm text-gray-600 hover:text-gray-900 underline"
        >
          Start New Meeting
        </button>
      </div>
    </div>
  );
};

export default MinutesView;